source 'https://rubygems.org'

gem 'rails', '4.1.0'
gem 'spring',        group: :development
gem 'sqlite3'
gem 'rails-lineman'
gem 'uglifier', '>= 1.3.0'
gem 'active_model_serializers'

gem 'pry', group: [:development, :test]
